import numpy as np

# tables.py
HEALTH_CODES = {
    0: "OK",
    1: "LOW_BATTERY",
    2: "BAD_BATTERY",
    3: "SENSOR_FAILURE",
    4: "COMM_FAILURE",
    5: "GPS_FAILURE",
    6: "MOTOR_FAILURE"
}

# Optional metadata per health
HEALTH_ACTIONS = {
    "OK": "Continue mission",
    "LOW_BATTERY": "Slow down, prepare to return",
    "BAD_BATTERY": "Return home immediately",
    "SENSOR_FAILURE": "Reduce role or return home",
    "COMM_FAILURE": "Hover or move toward base",
    "GPS_FAILURE": "Hover, attempt GPS reacquire",
    "MOTOR_FAILURE": "Abort and land immediately"
}

def get_health_name(code: int) -> str:
    return HEALTH_CODES.get(code, "UNKNOWN")

def get_all_health_codes():
    """Returns a dict {code: name} for display in GUI"""
    return HEALTH_CODES

COMMAND_TABLE = {
    "IDLE": 0,
    "TAKEOFF": 1,
    "SEARCH": 2,
    "RETURN_HOME": 3,
    "LAND": 4,
    "ABORT_MISSION": 5,
    "RECHARGE": 6,
}

# Dynamic table for the search area
class SearchAreaTable:
    """Holds info about all boxes in the search grid."""

    def __init__(self, box_centers):
        """
        box_centers: list of (x, y) positions generated by SearchArea.
        """
        self.boxes = [
            {"id": i, "pos": pos, "owner": None, "base_value": 10.0, "searched": False}
            for i, pos in enumerate(box_centers)
        ]

    def assign_box(self, box_id, drone_id):
        """Assign a box to a drone."""
        for box in self.boxes:
            if box["id"] == box_id:
                box["owner"] = drone_id
                return
        raise ValueError(f"Box {box_id} not found")

    def get_box_for_drone(self, drone_id):
        """Return the box currently assigned to the given drone."""
        for box in self.boxes:
            if box["owner"] == drone_id:
                return box
        return None

    def calculate_points_for_drone(self, drone_id, drone_pos):
        """
        Calculate the score (value) of each box for a specific drone based on distance.
        The closer the drone is to the box, the higher the score.
        """
        drone_pos = np.array(drone_pos)
        scores = []
        for box in self.boxes:
            box_pos = np.array(box["pos"])
            dist = np.linalg.norm(drone_pos[:2] - box_pos)
            score = box["base_value"] / (1 + dist)  # Example cost function
            scores.append((box["id"], round(score, 2)))
        return scores

    def mark_box_searched(self, box_id):
        """Mark a box as searched."""
        for box in self.boxes:
            if box["id"] == box_id:
                box["searched"] = True
                return

    def summary(self):
        """Return a summary list of all boxes and their ownership."""
        return [
            {"id": b["id"], "pos": b["pos"], "owner": b["owner"], "searched": b["searched"]}
            for b in self.boxes
        ]
